'use strict';
console.log('Truth table 3 variables for disjuntion');
console.log('var1\t var2\t var3\t var1 || var2 || var3');
var var1 = true;
var var2 = true;
var var3 = true;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var1 = false;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var1 =false;
var2 = false;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var1 = false;
var2 = false;
var3 = false;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var1 = true;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var2 = true;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var2 = false;
var3 = true;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));
var1 = false;
var2 = true;
var3 = false;
console.log(var1 + '\t' + var2 +'\t'+ var3 +'\t'+ (var1 || var2 || var3));